nkolban/esp32-snippets

cpp_utils/WS2812.cpp, cpp_utils/WS2812.h
Insert new setHSBPixel to create rainbow effects.
=> setHSBPixel

cpp_utils/JSON.cpp, cpp_utils/JSON.h
These functions are useful in a personal project.
=> Simple contribution: 'size' and 'toString' functions have been added to JSONArray

cpp_utils/BLEAdvertising.cpp, cpp_utils/BLEUtils.cpp
=> Fix missing semicolons

cpp_utils/BLEAdvertisedDevice.cpp, cpp_utils/BLEAdvertisedDevice.h, cpp_utils/BLEAdvertising.cpp, cpp_utils/BLEAdvertising.h, cpp_utils/BLECharacteristic.cpp, cpp_utils/BLECharacteristic.h, cpp_utils/BLECharacteristicMap.cpp, cpp_utils/BLEClient.cpp, cpp_utils/BLEClient.h, cpp_utils/BLEDescriptor.cpp, cpp_utils/BLEDescriptor.h, cpp_utils/BLEDescriptorMap.cpp, cpp_utils/BLERemoteService.cpp, cpp_utils/BLERemoteService.h, cpp_utils/BLEServer.cpp, cpp_utils/BLEServer.h, cpp_utils/BLEService.cpp, cpp_utils/BLEService.h, cpp_utils/BLEServiceMap.cpp
Code changes for https://github.com/nkolban/esp32-snippets/issues/31
Fell free to edit anything
=> Provide signatures to allow BLEUUID as string

BLE/scanner/README.md, BLE/scanner/ble1.c
Code refactored to dump more information
For details see the updated README.MD
=> Code updated to SDK v2.1

cpp_utils/WebServer.cpp
The functions did not work due to the loop not assembling the header string properly.
=> Fix WebServer headers

cpp_utils/WebServer.cpp, cpp_utils/WebServer.h
Now if the file is too big, the WebServer will send it in chunks instead. You can specify how big is too big in the definition on top of WebServer.h
=> Add sending files by chunks support.

cpp_utils/WebServer.cpp
=> If i opened 192.168.4.1 without any path after, the esp would crash

cpp_utils/BLEAdvertisedDevice.cpp, cpp_utils/BLEAdvertisedDevice.h, cpp_utils/tests/BLETests/SampleClient.cpp, cpp_utils/tests/BLETests/SampleClient_Notify.cpp, cpp_utils/tests/BLETests/SampleServer.cpp
=> Refactoring BLEAdvertisedDevice + update examples

.gitignore, cpp_utils/BLEClient.cpp, cpp_utils/BLEDevice.cpp
To free about 30kB RAM use this(best to use in app_main, before any interaction with bluetooth):
`	esp_bt_controller_mem_release(ESP_BT_MODE_CLASSIC_BT);
`
=> Fix issue #157

cpp_utils/BLERemoteService.cpp, cpp_utils/BLERemoteService.h, cpp_utils/HttpServer.cpp, cpp_utils/SockServ.cpp
Should be backward compatible.
=> Implementation of #184

cpp_utils/BLECharacteristic.cpp, cpp_utils/BLECharacteristic.h, cpp_utils/BLEClient.cpp, cpp_utils/BLEClient.h, cpp_utils/BLESecurity.cpp, cpp_utils/BLESecurity.h, cpp_utils/BLEServer.cpp, cpp_utils/BLEServer.h, cpp_utils/SampleSecureClient.cpp, cpp_utils/SampleSecureServer.cpp
We have introduced ble security. Security level introduced:
- encryption
- authentication
- authorization
Solving issues #69 and #260
=> Introduced BLE security

cpp_utils/BLEAdvertising.cpp, cpp_utils/BLEAdvertising.h
=> IBeacon fix #196

cpp_utils/BLEClient.cpp, cpp_utils/BLEClient.h, cpp_utils/BLEDescriptor.cpp, cpp_utils/BLEDescriptor.h, cpp_utils/BLEDevice.cpp, cpp_utils/BLEDevice.h, cpp_utils/BLESecurity.cpp, cpp_utils/BLESecurity.h, cpp_utils/BLEServer.cpp, cpp_utils/BLEServer.h, cpp_utils/tests/BLETests/security/SampleClient_Encryption.cpp, cpp_utils/tests/BLETests/security/SampleClient_authentication_numeric_confirmation.cpp, cpp_utils/tests/BLETests/security/SampleClient_authentication_passkey.cpp, cpp_utils/tests/BLETests/security/SampleSecureClient.cpp, cpp_utils/tests/BLETests/security/SampleSecureServer.cpp, cpp_utils/tests/BLETests/security/SampleServer_Encryption.cpp, cpp_utils/tests/BLETests/security/SampleServer_authentication_numeric_confirmation.cpp, cpp_utils/tests/BLETests/security/SampleServer_authentication_passkey.cpp, cpp_utils/tests/BLETests/security/SampleServer_authorization.cpp, cpp_utils/tests/BLETests/security/app_main_security.cpp
=> Security redesign + examples

cpp_utils/HttpServer.cpp, cpp_utils/HttpServer.h, cpp_utils/Socket.cpp, cpp_utils/Socket.h
=> Add timeout related to issue #322

cpp_utils/HttpResponse.cpp, cpp_utils/HttpResponse.h, cpp_utils/HttpServer.cpp
=> Move file serving to HttpResponse #342

cpp_utils/Makefile.arduino
https://github.com/nkolban/esp32-snippets/issues/365 point 2
=> add missing BLE2904.* files for arduino build

cpp_utils/Task.cpp, cpp_utils/Task.h
for setting the core number the task has to run on.
=> Added Task::setCore(BaseType_t coreId)

cpp_utils/Socket.cpp
Handling the partial writes in Socket::send also solves a similar issue for WebSockets.
=> Handle partial writes for issue #377

networking/bootwifi/README.md
Added and Example "main.c" to networking/bootwifi/README.md based on a comment by @chegewara https://github.com/nkolban/esp32-snippets/issues/245#issuecomment-350034132
=> Added an Example based on comment by @chegewara

cpp_utils/WiFi.cpp
Fix for issue #421 - WiFi::connectAP doesn't always return
=> Retry if esp_wifi_connect fails to connect

cpp_utils/CPPNVS.cpp, cpp_utils/CPPNVS.h, cpp_utils/WiFi.cpp, cpp_utils/WiFi.h
also expose a function in wifi to get connected state.
=> stop NVS get from crashing if the value hasn't been set yet,

cpp_utils/RESTClient.cpp, cpp_utils/RESTClient.h
Added (long)response_code return values to get and post methods to facilitate test for successful completion.
=> Added (long)response_code return values to get and post methods 

cpp_utils/BLEClient.cpp
=> reset m_haveServices in clearServices()

cpp_utils/BLEClient.cpp
This allows to avoid infinit lock in situations, where DISCONNECT occurs during long calls
=> Call give() to all m_semaphore***CmplEvt on disconnect

cpp_utils/BLEServer.cpp, cpp_utils/BLEServer.h, cpp_utils/BLEService.cpp, cpp_utils/BLEService.h, cpp_utils/BLEServiceMap.cpp
=> multiple services with the same uuid, first try

cpp_utils/BLEDevice.cpp
This change switches low level init to Arduino's methods when Arduino is detected. Also does not error out if BT is already initialised (in case another library has classic BT enabled, etc)
=> Add Arduino compatibility to BLEDevice::init

cpp_utils/BLEDevice.cpp, cpp_utils/BLEDevice.h, cpp_utils/BLEServer.cpp, cpp_utils/BLEServer.h
#647 with backward compatibility
=> move m_bleAdvertising to BLEDevice

cpp_utils/I2C.cpp, cpp_utils/I2C.h
Added ability to specify pullup resistor state on `i2c->init()`.
=> I2C: Configurable pullups

cpp_utils/Memory.cpp
Fixed some variable sizes in Memory class
=> Memory.cpp: variable size fixes

cpp_utils/MFRC522.cpp
Should solve issue https://github.com/nkolban/esp32-snippets/issues/61
SPI slave select and release (setting the _chipSelectPin high or low at each transfer) were missing. The MFRC522.h library should now work on ESP32 using ESP-IDF.
=> Add SPI slave select and release when reading / writting registers

cpp_utils/BLEDevice.cpp
Reverts nkolban/esp32-snippets#696
Causes #705
=> Revert "Release memory from CLASSIC_BT when not enabled"

cpp_utils/BLEAdvertisedDevice.cpp, cpp_utils/BLEAdvertisedDevice.h, cpp_utils/BLEAdvertising.cpp, cpp_utils/BLEAdvertising.h, cpp_utils/BLECharacteristic.cpp, cpp_utils/BLECharacteristic.h, cpp_utils/BLEClient.cpp, cpp_utils/BLEClient.h, cpp_utils/BLEDescriptor.cpp, cpp_utils/BLEDescriptor.h, cpp_utils/BLEDescriptorMap.cpp, cpp_utils/BLEDevice.cpp, cpp_utils/BLEDevice.h, cpp_utils/BLERemoteCharacteristic.cpp, cpp_utils/BLERemoteCharacteristic.h, cpp_utils/BLERemoteService.cpp, cpp_utils/BLERemoteService.h, cpp_utils/BLEScan.cpp, cpp_utils/BLEServer.cpp, cpp_utils/BLEServer.h, cpp_utils/BLEService.cpp, cpp_utils/BLEService.h, cpp_utils/BLEServiceMap.cpp, cpp_utils/BLEUUID.cpp, cpp_utils/BLEUtils.cpp, cpp_utils/GeneralUtils.cpp
I am merging features branch to master, but if there will be any issue with it i will revert this PR. I've been trying to test it as much as i could.
There is many updates, changes (most changes has been wrote with backward compatibility), new features.
Most important changes are:
- multi connection, for both direction, one esp32 client to multiple servers and one esp32 to multiple clients; i didnt test it but it should work many clients (servers) to one esp32 to multiple servers (clients
- some changes in BLEScan, BLEAdvertisedDevice and BLEAdvertising,
- i hope there is one more issue left with semaphores, but i have to think how to fix it.
=> Features, bugfixes and changes

cpp_utils/BLEClient.cpp, cpp_utils/BLEDevice.cpp, cpp_utils/BLERemoteCharacteristic.cpp, cpp_utils/BLERemoteCharacteristic.h, cpp_utils/BLERemoteService.cpp, cpp_utils/BLEUtils.cpp
https://github.com/nkolban/esp32-snippets/issues/751#issuecomment-454678707
=> fixed bugs

cpp_utils/BLEAdvertisedDevice.h, cpp_utils/BLECharacteristic.cpp, cpp_utils/BLECharacteristic.h, cpp_utils/BLEClient.cpp, cpp_utils/BLEClient.h, cpp_utils/BLEDevice.cpp, cpp_utils/BLEDevice.h, cpp_utils/BLERemoteCharacteristic.cpp, cpp_utils/BLERemoteCharacteristic.h, cpp_utils/BLEServer.cpp, cpp_utils/BLEServer.h
Bugfix: write long characteristic value
Bugfix: memory leak in BLERemoteCharacteristic
Bugfix: BLEClient use gattc_if for connections
Add: add delete BLEClient callbacks to avoid memory leak
Add: add BLEServer disconnect function
=> Few bugfixes and add functions

cpp_utils/BLESecurity.cpp, cpp_utils/BLESecurity.h
To use it:
```
BLESecurity *pSecurity = new BLESecurity();
pSecurity->setStaticPIN(123456); 
```
=> Add static pin feature

cpp_utils/BLECharacteristic.cpp, cpp_utils/tests/BLETests/Arduino/BLE_client/BLE_client.ino
=> Minor fixes
