nkolban/esp32-snippets

- hardware/displays/U8G2/test_SSD1306_i2c.c
- hardware/displays/U8G2/u8g2_esp32_hal.c
- hardware/displays/U8G2/u8g2_esp32_hal.h
Adding i²C to the u8g2_esp32_hal and include a sample task
- still don't know why the i²C have to be set (0x3C)
- still don't know why the I²C commandcode have to be added (0x00 or 0x40)
> I²C for u8g2 with ssd1306

- hardware/displays/U8G2/u8g2_esp32_hal.c
Adding back SPI init removed by mistake in i2c support commit.
> hardware/display/U8G2: add back missing SPI init

- cpp_utils/tests/BLETests/Arduino/BLE_uart/BLE_uart.ino
Combines the Notify and Write examples to create a basic UART example
that works with the Nordic nRF Android app and many others. Could use a
Print function and possibly read function, but basic RX/TX does work.
> BLE_uart example

- cpp_utils/Makefile.arduino
because this file doesn't exist any more in the current version and building for the Arduino fails then.
> Arduino Makefile: BLEServerCallback.cpp not existent

- hardware/displays/U8G2/u8g2_esp32_hal.c
The variable name changed from address to addr in esp-idf, see this
commit:
https://github.com/espressif/esp-idf/commit/ed1d084aeaef1c7216004354bd5b1a08f4a584cf#diff-c3da310493525a7302b298b32f3ac781
> Changed variable name (addr) in struct spi_transaction_t

- cpp_utils/Task.cpp
- cpp_utils/Task.h
I've added two new method to the Taks class. Namely "setPriority" and "setName" which sould be self explenatory.
Additionally there was the log line
ESP_LOGD(tag, "<< runTask: taskName=%s", pTask->m_taskName.c_str());
that would never be called the way it was located in the code. I moved the call prior to calling the stop() method.
> Added methods to Task class.

- hardware/displays/Adafruit_SSD1306-Library/Adafruit_SSD1306.cpp
- hardware/displays/Adafruit_SSD1306-Library/Adafruit_SSD1306.h
- hardware/displays/Adafruit_SSD1306-Library/examples/main/component.mk
- hardware/displays/Adafruit_SSD1306-Library/examples/main/main.cpp
- hardware/displays/Adafruit_SSD1306-Library/examples/main/tests.cpp
SSD1306 driver should have be faster about 2 with SPI clock 100kHz, and about 20 times with SPI clock 10Mhz.
> Optimization in display function to speed up drawing, added esp-idf example

- hardware/displays/U8G2/test_SSD1306.c
- hardware/displays/U8G2/test_SSD1306_i2c.c
- hardware/displays/U8G2/u8g2_esp32_hal.c
- hardware/displays/U8G2/u8g2_esp32_hal.h
Hi,
I found your snippets in the process of getting to work my cheap esp32 board. In particular TTGO Esp32 OLED+18650. It uses ssd1306 128x64 over I2C.
I followed what Luca Dentella wrote (http://www.lucadentella.it/en/2017/10/30/esp32-25-display-oled-con-u8g2/) , but was not able to get it running. It worked with other libs for ssd1306, but not u8g2 and this hal. 
It turned out that the ESP32 hal  was incorrectly sending each data byte as a separate I2C transaction (with address, command byte etc)
I corrected that and made some cleanup in the file: mainly removed dead code, fixed some debugging info, and merged gpio_delay functions. I think gpio_delay functions are only mcu specific not bus specific.
I tested that with SSD1306 using I2C. I don't have any other hardware to test it …
> Bug fix and cleanup. I2C version of HAL was not functional with current u8g2 version

- cpp_utils/I2C.cpp
as example for the bm280:
i2cBus.setAddress(0x77);
i2cBus.beginTransaction();
i2cBus.write(BME280_CHIP_ID_ADDR, true);
i2cBus.start();
i2cBus.read(&chip_id, false);
i2cBus.endTransaction();
> after an start it should be resend the address

- cpp_utils/BLECharacteristic.cpp
- cpp_utils/BLECharacteristic.h
- cpp_utils/FreeRTOS.cpp
- cpp_utils/FreeRTOS.h
- cpp_utils/tests/BLETests/Arduino/BLE_notify/BLE_notify.ino
- cpp_utils/tests/BLETests/Arduino/BLE_uart/BLE_uart.ino
See comments in issue #209:
- Useless semaphore polling removed. 
- Examples for BLE_uart and BLE_notify adapted correspondingly.
Changes tested with the samples mentioned above.
> Issue #209 - reverted to single threaded operation

- cpp_utils/NeoPixelWiFiEventHandler.cpp
- cpp_utils/NeoPixelWiFiEventHandler.h
- cpp_utils/WiFiEventHandler.cpp
- cpp_utils/WiFiEventHandler.h
- cpp_utils/cpp_utils
Please review this request and decline it if brakes your code because i changed the parameter for got_ip.
Briefly: Added two more methods:
**staScanDone(system_event_sta_scan_done_t info)**
**staAuthChange(system_event_sta_authmode_change_t info)**
The event for 6 more methods is passed to the overridden method the same way as **staGotIp** so i can use it like:
> virtual esp_err_t apStaConnected(system_event_ap_staconnected_t info)
> {
>      printf("New client connected. ");
>      printf("MAC Address : %02x:%02x:%02x:%02x:%02x:%02x\n",
>      (unsigned char) info.mac[0],
>      (unsigned char) info.mac[1],
>      (unsigned char) info.mac[2],
>      (unsigned char) info.mac[3],
>      (unsigned char) info.mac[4],
>      (unsigned char) info.mac[5]);
> }
Output: **New client connected. …
> Extend WiFiEventHandler. Add info arguments.

- cpp_utils/BLEAdvertisedDevice.cpp
- cpp_utils/BLEAdvertisedDevice.h
> Add ServiceData GAP event

- hardware/gps/Fragments/log_to_console.c
- hardware/gps/gps/main/gps.c
Previously the uart paramter has been ignored and UART1 has
always been used to read a line from GPS.
> Use uart given as parameter to read line from GPS

- cpp_utils/WebSocket.cpp
- cpp_utils/WebSocket.h
One could argue that the sendType paramater is superflous for this call.
> Added WebSocket::send for binary data (issue #380)

- cpp_utils/BLEAdvertising.cpp
- cpp_utils/BLEAdvertising.h
It should be possible to create an Apple iBeacon using the setFlags() and setManufacturerData() methods for the BLEAdvertisementData class.  But the Apple specification calls for a 100ms minimum and maximum transmission interval.
This minor change would add two setter methods to BLEAdvertising to setMaxInterval(uint16_t maxinterval) and setMinInterval(uint16_t maxinterval).  
In addition to the iBeacon capability, the ability to increase advertising interval will extend life of battery operated devices somewhat dramatically.  The BLE spec allows intervals up to about 10 seconds in 0.625 ms increments.
> Advertising Interval

- cpp_utils/PubSubClient.cpp
- cpp_utils/PubSubClient.h
Here is my portation of the common PubSubClient class. Now you can use these class with the cpp-utils to connect to a generic mqqt broaker (not only AWS).
Notice: Only the basic functions working so faw.
What we can do better:
- support QoS 1, QoS 2 Level
- add a "useSSL()"-function
- do a stresstest
> Add a generic MQTT client class (PubSubClient) solve #398

- cpp_utils/HttpParser.cpp
- cpp_utils/HttpParser.h
The HttpParser class contains most of the functionality that is needed to also parse http response messages. I propose to add the method void HttpParser::parseResponse(std::string message) for this purpose. 
See issue #415
> Allow HttpParser to parse response messages as well as request messages

- cpp_utils/CPPNVS.cpp
sorry about this, while my previous PR definitely fixed the crashing it also caused the NVS code to not actually get any values. This commit fixes it so that if it gets an error when doing the length check then it will return the error code it got from esp-idf otherwise continue normally.
Sorry I didn't see this the first time around and have introduced a bug, looking at the code now it's plainly obvious.
> only return NVS error code if it is not OK

- cpp_utils/BLEService.cpp
Made the fix that @chegewara  proposed. I was confused by the error and found this github issue in the repository: [Issue](https://github.com/nkolban/esp32-snippets/issues/175). I changed the error to a warning, because it actually is possible to create multiple characteristics with the same UUID.
> Replaced error message for double characteristics

- cpp_utils/HttpParser.cpp
When a POST (or PUT) message has no body, then socket::receive will return -1. Attempting to create a std::string with this length causes an exception.
> Prevents exception when parsing HTTP POST message without a body

- cpp_utils/GeneralUtils.cpp
- cpp_utils/GeneralUtils.h
- cpp_utils/WiFi.cpp
- cpp_utils/WiFi.h
- networking/bootwifi/BootWiFi.cpp
Prior to this change, `bootWiFi2` would sometimes return before the ESP32 had successfully connected to WiFi - specifically when a `staDisconnected` event was received.  
This causes `BootWiFi::boot()` to hang, waiting indefinitely on `m_completeSemaphore.wait("boot");`.  This happens because the only place the semaphore is resolved is in the `staGotIp` event handler.  Unfortunately, the `staGotIp`event never occurs because bootWiFi2 has returned and so there are no retry attempts.
This change ensures that ESP32 has successfully connected before BootWiFi returns (or keeps trying forever).
> Modified bootWiFi2 method to call m_wifi.connectAP forever or until it successfully connects

- networking/bootwifi/BootWiFi.cpp
- networking/bootwifi/BootWiFi.h
Prior to this change, BootWiFi::boot would hang on m_completeSemaphore.wait("boot") if WiFi::connectAP received SYSTEM_EVENT_STA_DISCONNECTED.  
This commit changes 2 items:
1. After returning from m_wifi.connectAP, calls m_completeSemaphore.give() to ensure BootWiFi::boot does not hang. 
2. BootWiFi::boot returns ESP_OK if it successfully received a SYSTEM_EVENT_STA_GOT_IP event. Otherwise it returns the wifi_err_reason_t code.  
This way, the programmer can then handle errors in a distinct manner.
> Additional to PR #475.  Addresses BootWiFi::boot hanging

- cpp_utils/BLEServer.cpp
- cpp_utils/PubSubClient.cpp
- cpp_utils/SockServ.cpp
Added three missing semi-colons.
Removed unecessary header (gatt_api.h). For some reason, with latest esp-idf, my toolchain can't resolve this header location. Anyway, the header is not required by BLEServer.cpp.
> Typo fixes

- cpp_utils/tests/BLETests/SampleHIDKeyboard.cpp
via the callback for onDisconnect, the keyboard task is stopped.
It seems, that in addition, the task itself deletes itself again via ::vTaskDelete(NULL).
This leads to a crash by dereferencing the already missing TCB.
Used example: https://github.com/asterics/esp32_mouse_keyboard/tree/newBLE
```
I (757) HAL_BLE: Advertising started!
--- debug messages added to Task::start()---
I (2327) task: start, m_handle before: 0
I (2327) task: start, m_handle after: 3FFE6EB8
I (2327) task: start, m_handle before: 0
I (2337) task: start, m_handle after: 3FFE8FC4
E (2427) BT: Call back not found for application conn_id=3
I (2427) BLEDevice: ESP_GATTS_MTU_EVT, MTU 517
I (2447) HAL_BLE: special keys: 1
...... BLE sending keyboard & mouse .....
Disabling BLE on Win10 (and Android):
I (38337) HAL_BLE: …
```
> Removed vTaskDelete, avoiding crashes with Task::stop() called

- cpp_utils/tests/BLETests/Arduino/BLE_uart/BLE_uart.ino
Lots of apps (e.g. Blynk, RemoteXY) do not find the device during scanning on iOS, whereas other devices with the same service UUID are found. The origin of the problem is that in the advertisment, the service UUID is missing. This extra line fixes this problem.
> BLE_UART example: Add Service UUID advertising (iOS support)

- cpp_utils/SPI.cpp
In `SPI::init` the missing initialization of `bus_config.flags` resulted in a boot failure and the message "spiwp pin required." from `spicommon_bus_initialize_io` in spi_common.c.
Similarly the dev_config.flags now needs to be initialized to prevent a boot failure and corresponding message from `spi_bus_add_device` in spi_master.c.
See also #485
> Set spi_bus_config_t and spi_device_interface_config_t flags

- cpp_utils/BLEServer.cpp
- cpp_utils/BLEServer.h
- cpp_utils/BLEService.cpp
- cpp_utils/BLEService.h
- cpp_utils/BLEServiceMap.cpp
Changes in relation to #534 .
To remove a service call `removeService` method on BLEServer object with the service you want to remove.
> BLE Remove Service Support

- cpp_utils/WiFi.cpp
- cpp_utils/WiFi.h
I made this change because I needed a way to keep the esp32's own Access Point running while it connected to a remote AP. 
I've tested this change with an older version of esp32-snippets (when connectAP still returned bool) but apart from the return type the function appears to be the same.
Once I get my current feature sorted out I'm planning to upgrade to master so I will test it then, but it seemed like a small change so might as well raise a PR at least for discussion.
> Option to choose WIFI_MODE_APSTA when connecting to an AP

- cpp_utils/BLERemoteDescriptor.cpp
I initially issued nkolban/ESP32_BLE_Arduino#17 but was told ([here](https://github.com/nkolban/esp32-snippets/issues/391#issuecomment-402993009)) that this is the master repo, hence this PR :D
> Handle `response` argument for BLERemoteDescriptor#writeValue()

- cpp_utils/BLESecurity.h
Make all the methods pure virtual.
Some of the methods were virtual, but without local definitions,
this creates an error during linking.
I think there shouldn't be any default behavior for this class.
This will fix issue #412
> FIX: BLESecurity.h -> BLESecurityCallbacks.

- cpp_utils/tests/task_i2c_scanner.cpp
Fix params passed to i2c.init() to include DEVICE_ADDRESS in the first position. Otherwise SDA becomes SCL_PIN and SCL becomes Default.
(I think I've got this right, but couldn't force compilation on the standalone branch, only as part of the components folder in another ESP32 project).
> Bug fix for cpp_utils/tests/task_i2c_scanner.cpp

- cpp_utils/I2C.cpp
I've noticed that `init`'s `clockSpeed` parameter is only used in `ESP_LOGD`. That surely can't be right.
> I2C: fix ignored clockSpeed

- hardware/displays/U8G2/u8g2_esp32_hal.c
if we don't set bus_config to all zero, a wrong bus_config.flag may have some random bug
> Fix  a bug in U8G2 HAL SPI initialize

- cpp_utils/BLECharacteristic.cpp
- cpp_utils/BLECharacteristic.h
hi there,
for a year i was using `getValue().c_str()` to get raw characteristic value to pass to C function in couple of my applications.
It turns out raw `uint8_t` pointer to data already exists and implemented. I just added proper proxy functions to make them available in arduino and ease development a bit :)
> add `getData` proxy to BLECharacteristic

- cpp_utils/BLEUtils.cpp
Added switch case to fix compilation.
Introduced in https://github.com/espressif/esp-idf/commit/9fb188a1d98fabec28d923c2db87961c2b9fa01e
> Fix compilation against latest ESP-IDF

- cpp_utils/NeoPixelWiFiEventHandler.cpp
Neopixel event handler seems to be using sprintf for logging purposes. This ignores the minimum level set for logging in config (also I'm not sure if that'd even work).
> Sanitize Neopixel logging

- cpp_utils/BLEService.cpp
- cpp_utils/BLEService.h
Last parameter for `esp_ble_gatts_create_service`, `num_handle`, is of type uint16_t. There's no point of having `m_numHandles` to be uint32_t.
> BT: uint16_t numHandles

- cpp_utils/FreeRTOS.cpp
Some methods that return a bool, do not check a result for `pdTRUE`, therefore an error would never be triggered.
> FreeRTOS: Check if value is pdTRUE

- cpp_utils/FreeRTOS.cpp
- cpp_utils/FreeRTOS.h
Return from `Ringbuffer::send` is of type `uint32_t`, where it should be `bool`, just like underlying function's result.
> Ringbuffer::send returns bool

- cpp_utils/FreeRTOS.cpp
- cpp_utils/FreeRTOS.h
Stack size is defined as `int`, whereas underlying function asks for `const uint32_t`. Passing in `uint32_t` satisfies the criteria and excludes ambiguity.
> FreeRTOS: Stack size is uint32_t

- cpp_utils/GPIO.cpp
Light fixes to GPIO class.
- `GPIO::read` has implicit conversion from `int` to `bool`.
- `gpio_set_level` accepts a `int` argument, `bool` given.
> GPIO: Add checks for bool returns

- cpp_utils/PubSubClient.cpp
- cpp_utils/PubSubClient.h
Also, `PubSubClient::readPacket` returns a `uint16_t` where it should be returning a `size_t` (number of bytes read).
> PubSub: pass pdTRUE instead of true

- cpp_utils/BLEDevice.cpp
There was a FIXME marker, stating that reply is pending from esp-idf team. Seems like issue has been resolved and we can use `esp_bt_controller_mem_release` safely now. (https://github.com/espressif/esp-idf/issues/1162)
I have removed the `esp_bt_controller_enable(ESP_BT_MODE_BLE)` as it causes BT controller failing to start when config has `CLASSIC_BT_ENABLED=y`. There's no more `ESP_BT_MODE_BLE`, only `ESP_BT_MODE_BTDM`, therefore I've cut out most of `#ifndef` block. (https://github.com/espressif/esp-idf/issues/405)
> Release memory from CLASSIC_BT when not enabled

- cpp_utils/PWM.cpp
Passing a `bool` to function that expects an `int`. This fixes that.
> PWM: idle level is bool

- cpp_utils/WebSocket.cpp
There's no need for opcodes to be `int`s, uint8_t is quite enough. In fact, that eliminates some implicit type conversion\casting.
I've changed `int`s to be `size_t`s where they represent the number of bytes, too.
> WebSocket: Opcodes are uint8_t

- cpp_utils/PCF8574.cpp
- cpp_utils/PCF8574.h
- cpp_utils/PCF8575.cpp
- cpp_utils/PCF8575.h
Changed I2C instance to be hosted on the heap for these two drivers.
Seems like PCF8575 is writing `uint16_t` whereas PCF8574 is operating on `uint8_t`s. I've changed the type to represent the structure better.
> PCF8574 & PCF8575: i2c on heap

- cpp_utils/BLERemoteCharacteristic.cpp
- cpp_utils/BLERemoteCharacteristic.h
Add access to remote address in BLERemoteCharacteristic to distinguish different servers with same characteristic uuid within notifyhandler
> Add access to remote address in BLERemoteCharacteristic

- cpp_utils/BLERemoteCharacteristic.h
**When:**
Compiling a project.
**Where:**
Line 54 in: BLEAddress  getRemoteAddress();
**Drops error:**
'BLEAddress' does not name a type
**My Solution:**
Add the include: #include "BLEAddress.h"
> Fix error:  'BLEAddress' does not name a type

- cpp_utils/CMakeLists.txt
ESP-IDF supports (in preview) CMake for generating projects. 
This PR adds CMake support for the `cpp_utils` component
> Add CMake support

- cpp_utils/BLEHIDDevice.cpp
I'm building a BLE HID keyboard and can confirm that the notify is necessary for the BT client (in this case a PC) to update its battery indicator. Tested under Linux with Gnome and Windows 10.
> Notify after setBatteryLevel

- cpp_utils/FreeRTOS.cpp
Fixes the problem of giving a mutex from a callback with the latest IDF. Also addresses an occasional assert that happens when the btc_task callback gives the semaphore and causes an assert due to both cores potentially writing m_owner concurrently.
> Fix semaphores in IDF & std::string assert.
